repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-json
        exclude: ".vscode/settings.json"
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: name-tests-test
        args: ["--django"]
      - id: pretty-format-json
        args: ["--autofix"]
        exclude: ".vscode/settings.json"

    # Autoflake
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--exclude=__init__.py",
          ]

    # Isort
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--settings-path=./backend/app/pyproject.toml"]

    # Black
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: ["--config=./backend/app/pyproject.toml", "--verbose"]

    # Flake
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          ["flake8-docstrings==1.6.0", "flake8-isort==4.1.1", "dlint==0.12.0"]
        args: [--config=./backend/app/.flake8]

    # MyPy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.931"
    hooks:
      - id: mypy
        additional_dependencies: ["tokenize-rt==3.2.0", "pydantic==1.9.0"]
        args: [--config-file=./backend/app/mypy.ini]

    # ESLint
  - repo: https://github.com/pre-commit/mirrors-eslint.git
    rev: "v8.7.0"
    hooks:
      - id: eslint
        files: \.{[jt]sx?$,vue}
        additional_dependencies:
          - eslint-plugin-vue

      # JSHint
  - repo: https://github.com/pre-commit/mirrors-jshint
    rev: "v2.13.3"
    hooks:
      - id: jshint
